Repository Cocktail-Wizard/Cocktail_Wizard, pull requests merged in 2024-04, with the labels that each got.

#83 Remettre barre recherche
  index.php
Labels: type: fix, work: clear, effort: 1, priority: 1, state: approved

#86 separation html et ajout cookie
  index.php
  pages/galerie.php
  pages/galerieConn.php
  ressources/scripts/connexionWeb.php
Labels: type: refactoring, work: clear, effort: 1, priority: 1, state: approved

#87 Ajout du tri des cocktails de la galerie
  index.php
  pages/galerie.php
  pages/galerie_connecte.php
  ressources/images/icone-calendrier.svg
  ressources/images/tete-fleche-bas.svg
  ressources/scripts/index.js
  ressources/scripts/outils.js
  ressources/styles/index.css
Labels: work: clear, effort: 2, priority: 4, state: approved, type: feature

#90 Ajout de la fonctionnalité de changement du mot de passe
  documentation/Script_procedures.sql
  ressources/api/fonctionAPIphp/paramJSONvalide.php
  ressources/api/modifierMotDePasse.php
  routes.php
Labels: effort: 1

#88 Ajout de la fonctionnalité de like des cocktails
  pages/galerie.php
  pages/galerie_connecte.php
  ressources/modeles/cocktail_modale.html
  ressources/scripts/index.js
  ressources/scripts/outils.js
Labels: work: clear, effort: 1, priority: 4, state: approved, type: feature

#91 Ajout de la fonctionnalité de commenter des cocktails
  ressources/modeles/cocktail_modale.html
  ressources/scripts/index.js
  ressources/styles/modale.css
Labels: work: clear, effort: 1, priority: 3, state: approved, type: feature

#92 🍪
  ressources/scripts/index.js
Labels: type: fix, work: clear, effort: 1, priority: 2, state: approved, type: cleanup

#93 Securisation du cookie du nom d'utilisateur
  ressources/scripts/connexionWeb.php
Labels: type: fix, work: clear, effort: 1, priority: 2, state: approved

#98 Cleanup d'une erreur quand il n'y a aucun commentaire pour un cocktail
  ressources/api/ajouterCommentaire.php
  ressources/api/getCocktailCommentaires.php
  ressources/scripts/index.js
  ressources/scripts/inscription.js
Labels: work: clear, effort: 🐭, priority: 4, state: approved, type: cleanup

#89 Ajout gestion image
  documentation/Script_insertion_donnee.sql
  documentation/Script_procedures.sql
  index.php
  pages/galerie_connecte.php
  ressources/api/ajouterCocktail.php
  ressources/api/connexion.php
  ressources/modeles/cocktail_modale.html
  ressources/scripts/connexion.js
  ressources/scripts/connexionWeb.php
  ressources/scripts/index.js
Labels: work: clear, effort: 🐶, priority: 2, state: pending, type: feature

#99 Ajout du lien vers "Mon bar" quand connecté
  pages/galerie.php
  pages/galerie_connecte.php
  pages/monbar.php
  ressources/images/icone-monbar.svg
  ressources/scripts/index.js
  ressources/styles/index.css
Labels: work: clear, effort: 🐭, priority: 3, state: approved, type: enhancement

#101 Ajout d'information d'utilisateur renvoyé par l'API
  documentation/Script_procedures.sql
  ressources/api/getUserInfo.php
  ressources/classephp/Utilisateur_Classe.php
Labels: effort: 🐭, priority: 4, state: approved, type: feature

#97 Feature/connexion base donnee
  documentation/Script_procedures.sql
  icone.ico
  pages/galerie.php
  pages/galerie_connecte.php
  pages/monbar.php
  ressources/api/fonctionAPIphp/InfoAffichageCocktail.php
  ressources/images/minus.svg
  ressources/images/plus.svg
  ressources/modeles/modale_profilUtilisateur.php
  ressources/modeles/modale_publication.php
  ressources/scripts/index.js
  ressources/scripts/monbar.js
  ressources/scripts/outils.js
  ressources/scripts/publication.js
  ressources/scripts/userprofile.js
  ressources/styles/index.css
  ressources/styles/main.css
  ressources/styles/monbar.css
  ressources/styles/publication.css
  ressources/styles/userprofile.css
  routes.php
Labels: work: complicated, effort: 🐋, priority: 1, state: pending, type: configurations, type: feature

#103 Fix erreur dans la gestion du cookie.
  pages/monbar.php
  ressources/scripts/monbar.js
  ressources/scripts/publication.js
Labels: effort: 🐭, priority: 2, type: bug

#104 Fix erreur API
  ressources/api/ajouterIngredientMonBar.php
  ressources/api/enleverIngredientMonBar.php
  ressources/api/getCocktailCommentaires.php
  ressources/api/getCocktails.php
  ressources/api/getIngredients.php
  ressources/api/getUserCocktails.php
  ressources/api/getUserInfo.php
  ressources/api/getUserIngredients.php
  ressources/api/getUserRecommandations.php
  ressources/api/rechercheCocktail.php
Labels: type: fix, work: clear, effort: 🐭, effort: 🐶, priority: 3, state: pending

#106 Fix de l'image des icones des icones par defaut
  ressources/scripts/index.js
Labels: type: fix, type: ui/ux, work: clear, effort: 🐭, priority: 2, state: approved

#107 Fix bug http response code
  .github/workflows/develop_test_azure_cocktailwizard.yml
  documentation/Script_procedures.sql
  pages/galerie.php
  pages/galerie_connecte.php
  pages/monbar.php
  ressources/api/ajouterIngredientMonBar.php
  ressources/api/config.php
  ressources/api/fonctionAPIphp/InfoAffichageCocktail.php
  ressources/classephp/Cocktail_Classe.php
  ressources/images/icone-galerie.svg
  ressources/modeles/modale_publication.php
  ressources/scripts/index.js
  ressources/scripts/outils.js
  ressources/styles/carte_cocktail.css
  ressources/styles/index.css
Labels: work: clear, effort: 🦁, priority: 2, state: approved, type: bug

#108 Ajout du bouton de déconnexion
  documentation/Script_procedures.sql
  ressources/modeles/modale_profilUtilisateur.php
  ressources/scripts/connexionWeb.php
  ressources/scripts/outils.js
  ressources/scripts/userprofile.js
  ressources/styles/userprofile.css
  routes.php
Labels: work: clear, effort: 🐶, priority: 2, state: approved, type: feature

#109 Supprime cocktails, commentaires et comptes API
  documentation/Script_procedures.sql
  ressources/api/supprimerCocktail.php
  ressources/api/supprimerCommentaire.php
  ressources/api/supprimerProfile.php
  routes.php
Labels: effort: 🐶, priority: 3, state: approved, type: feature

#113 Ajout des fonctionnalités dans mon bar
  documentation/Script_insertion_donnee.sql
  documentation/Script_procedures.sql
  pages/galerie.php
  pages/galerie_connecte.php
  pages/monbar.php
  ressources/api/getUserRecommandations.php
  ressources/api/rechercheUserRecommandations.php
  ressources/classephp/Cocktail_Classe.php
  ressources/modeles/cocktail_carte.html
  ressources/scripts/index.js
  ressources/scripts/monbar.js
  ressources/scripts/userprofile.js
  ressources/styles/carte_cocktail.css
  ressources/styles/index.css
  ressources/styles/monbar.css
Labels: effort: 🐶, priority: 2, state: approved

#115 Optimization/optimisations diverses
  ressources/scripts/connexion.js
  ressources/scripts/index.js
  ressources/scripts/inscription.js
  ressources/scripts/modale.js
Labels: type: optimization, work: clear, effort: 🐭, priority: 5, state: approved

#116 Ajout du lazy loading des cocktails/infinite scrolling
  documentation/Script_procedures.sql
  pages/galerie.php
  pages/galerie_connecte.php
  pages/monbar.php
  ressources/api/ajouterCocktail.php
  ressources/api/fonctionAPIphp/InfoAffichageCocktail.php
  ressources/api/fonctionAPIphp/authorisationAPI.php
  ressources/api/getCocktailCommentaires.php
  ressources/api/getCocktails.php
  ressources/api/getIngredients.php
  ressources/api/getUserCocktails.php
  ressources/api/getUserInfo.php
  ressources/api/getUserRecommandations.php
  ressources/api/rechercheCocktail.php
  ressources/api/rechercheUserRecommandations.php
  ressources/api/routageGETcocktail.php
  ressources/images/1490.gif
  ressources/modeles/modale_profilUtilisateur.php
  ressources/modeles/modale_publication.php
  ressources/scripts/index.js
  ressources/scripts/monbar.js
  ressources/scripts/userprofile.js
  routes.php
Labels: effort: 🐱, priority: 3, state: approved, type: feature

#117 Generation de la couleur des pastilles des cocktails selon l'alcool principal
  ressources/scripts/index.js
  ressources/scripts/monbar.js
  ressources/scripts/outils.js
Labels: type: ui/ux, work: clear, effort: 🐭, priority: 3, state: approved

#118 Clean Up
  .github/workflows/develop_cocktailwizard.yml
  .github/workflows/develop_test_azure_cocktailwizard.yml
  documentation/Script_insertion_donnee.sql
  documentation/Script_vues.sql
  ressources/api/ajoutIng.php
  ressources/api/ajouterCocktail.php
  ressources/api/ajouterCommentaire.php
  ressources/api/ajouterIngredientMonBar.php
  ressources/api/config.php
  ressources/api/dislikeCommentaire.php
  ressources/api/fonctionAPIphp/InfoAffichageCocktail.php
  ressources/api/fonctionAPIphp/authorisationAPI.php
  ressources/api/fonctionAPIphp/usernameToId.php
  ressources/api/getCocktailCommentaires.php
  ressources/api/getCocktails.php
  ressources/api/getIngredients.php
  ressources/api/getUserInfo.php
  ressources/api/getUserRecommandations.php
  ressources/api/modifierMotDePasse.php
  ressources/api/rechercheCocktail.php
  ressources/api/rechercheUserRecommandations.php
  ressources/api/routageGETcocktail.php
  ressources/api/supprimerCocktail.php
  ressources/api/supprimerCommentaire.php
  ressources/api/supprimerProfile.php
  ressources/classephp/Cocktail_Classe.php
  ressources/images/icone-galerie.svg
  ressources/images/info.svg
  ressources/images/minus.svg
  ressources/images/plus.svg
  ressources/modeles/modale_publication.php
  ressources/scripts/connexionWeb.php
  ressources/scripts/userprofile.js
  ressources/styles/index.css
  ressources/styles/monbar.css
  router.php
  routes.php
Labels: state: approved

#120 Suppression profile
  ressources/api/inscription.php
  ressources/scripts/userprofile.js
Labels: state: approved

#121 Correction de l'affichage mal aligné de l'alcool principal
  ressources/styles/carte_cocktail.css
Labels: type: fix, type: ui/ux, work: clear, effort: 🐭, priority: 3, state: blocked

#122 Simplification de la fonction `genererDegreDepuisString`
  ressources/scripts/outils.js
Labels: type: optimization, type: performance, work: clear, effort: 🐭, priority: 5

#119 Gestion des images utilisateurs
  documentation/Script_procedures.sql
  pages/galerie_connecte.php
  pages/monbar.php
  ressources/api/modifierImageProfil.php
  ressources/modeles/modale_profilUtilisateur.php
  ressources/scripts/userprofile.js
  ressources/styles/userprofile.css
  routes.php
Labels: state: approved

#124 Sécurisation de l'API
  documentation/Script_procedures.sql
  ressources/api/ajouterCocktail.php
  ressources/api/ajouterCommentaire.php
  ressources/api/ajouterIngredientMonBar.php
  ressources/api/config.php
  ressources/api/connexion.php
  ressources/api/dislikeCocktail.php
  ressources/api/dislikeCommentaire.php
  ressources/api/enleverIngredientMonBar.php
  ressources/api/fonctionAPIphp/authorisationAPI.php
  ressources/api/getUserCocktails.php
  ressources/api/getUserInfo.php
  ressources/api/getUserIngredients.php
  ressources/api/getUserRecommandations.php
  ressources/api/likeCocktail.php
  ressources/api/likeCommentaire.php
  ressources/api/modifierImageProfil.php
  ressources/api/modifierMotDePasse.php
  ressources/api/rechercheUserRecommandations.php
  ressources/api/supprimerCocktail.php
  ressources/api/supprimerCommentaire.php
  ressources/api/supprimerProfile.php
  ressources/scripts/connexionWeb.php
Labels: type: security, priority: 2, state: approved

#125 Suppression d'un cocktail par son auteur
  ressources/images/icone-corbeille.svg
  ressources/modeles/cocktail_modale.html
  ressources/scripts/index.js
  ressources/styles/modale.css
Labels: work: clear, effort: 🐭, priority: 2, state: approved, type: feature

#127 Ajout lien barre en bas SAQ
  ressources/modeles/cocktail_carte.html
  ressources/scripts/index.js
  ressources/scripts/monbar.js
Labels: work: clear, effort: 🐭, priority: 3, state: approved, type: enhancement

#128 Ajout de la demande de confirmation de suppression d'un cocktail
  ressources/scripts/index.js
Labels: work: clear, effort: 🐭, priority: 4, state: approved, type: enhancement

#129 Ajout alerte si soumission d'un nouveau cocktail est invalide
  ressources/scripts/publication.js
Labels: type: ui/ux, work: clear, effort: 🐭, priority: 3, state: approved, type: enhancement

#130 Utilisation box-shadow pour les icones oranges
  ressources/styles/connexion.css
  ressources/styles/index.css
  ressources/styles/inscription.css
  ressources/styles/modale.css
  ressources/styles/monbar.css
  ressources/styles/publication.css
  ressources/styles/userprofile.css
Labels: type: ui/ux, work: clear, effort: 🐭, priority: 4, state: approved
